#!/usr/bin/env python3
"""
Global hotkey daemon for Whisper GUI using xbindkeys
Monitors CTRL+ALT+SHIFT+R and signals GUI to toggle recording
"""

import os
import sys
import signal
import subprocess
import time
import tempfile
import shutil
from pathlib import Path


class HotkeyDaemon:
    """Global hotkey daemon using xbindkeys configuration"""

    def __init__(self):
        self.running = True
        self.xbindkeys_process = None
        self.config_file = None

        # Register signal handlers
        signal.signal(signal.SIGTERM, self._handle_signal)
        signal.signal(signal.SIGINT, self._handle_signal)

    def _handle_signal(self, signum, frame):
        """Handle termination signals"""
        print(f"Received signal {signum}, shutting down...")
        self.cleanup()
        sys.exit(0)

    def find_gui_pid(self):
        """Find GUI process PID from lock file"""
        lock_file = Path.home() / ".whisper" / "app.lock"
        if lock_file.exists():
            try:
                with open(lock_file, 'r') as f:
                    pid_str = f.read().strip()
                    if pid_str and pid_str.isdigit():
                        pid = int(pid_str)
                        # Verify process still exists
                        try:
                            os.kill(pid, 0)
                            return pid
                        except (OSError, ProcessLookupError):
                            pass
            except Exception as e:
                print(f"⚠️ Error reading lock file: {e}")

        return None

    def get_x11_environment_from_process(self, pid):
        """Read X11 environment variables from a process"""
        try:
            environ_file = Path(f"/proc/{pid}/environ")
            if environ_file.exists():
                with open(environ_file, 'rb') as f:
                    environ_data = f.read()
                    env_vars = environ_data.split(b'\0')
                    env_dict = {}
                    for env in env_vars:
                        if b'=' in env:
                            key, val = env.split(b'=', 1)
                            env_dict[key.decode('utf-8')] = val.decode('utf-8')

                    # Extract X11-related variables
                    x11_env = {}
                    for key in ['DISPLAY', 'XAUTHORITY', 'WAYLAND_DISPLAY']:
                        if key in env_dict:
                            x11_env[key] = env_dict[key]

                    return x11_env
        except Exception as e:
            print(f"⚠️ Error reading process environment: {e}")

        return {}

    def create_xbindkeys_config(self):
        """Create xbindkeys configuration file"""
        # Get GUI PID
        gui_pid = self.find_gui_pid()
        if not gui_pid:
            print("⏳ Waiting for GUI process...")
            for _ in range(30):  # Wait up to 30 seconds
                time.sleep(1)
                gui_pid = self.find_gui_pid()
                if gui_pid:
                    break

        if not gui_pid:
            print("❌ Could not find GUI process")
            return None

        # Create temporary config file
        config = tempfile.NamedTemporaryFile(
            mode='w',
            suffix='.xbindkeysrc',
            delete=False,
            dir=Path.home()
        )

        # xbindkeys config format:
        # "command"
        #   key_modifiers + key
        # Note: use "control" not "ctrl", "mod1" is alt
        config_content = f'''# Whisper Global Hotkey Configuration
# Generated by whisper_hotkey_daemon.py

"kill -USR1 {gui_pid}"
   control + shift + mod1 + r

# End of xbindkeys configuration
'''

        config.write(config_content)
        config.close()

        print(f"✅ Created xbindkeys config: {config.name}")
        print(f"✅ Found GUI process (PID: {gui_pid})")

        return config.name

    def start_xbindkeys(self):
        """Start xbindkeys with our configuration"""
        # Check if xbindkeys is installed
        # Try multiple paths
        xbindkeys_paths = [
            '/usr/bin/xbindkeys',
            '/usr/local/bin/xbindkeys'
        ]

        xbindkeys_path = None
        for path in xbindkeys_paths:
            if Path(path).exists():
                xbindkeys_path = path
                break

        # If not found in standard locations, try shutil.which()
        if not xbindkeys_path:
            xbindkeys_path = shutil.which('xbindkeys')

        if not xbindkeys_path:
            print("❌ xbindkeys not found!")
            print("   Install with: sudo apt install xbindkeys")
            return False

        print(f"✅ xbindkeys found at: {xbindkeys_path}")

        # Create config
        self.config_file = self.create_xbindkeys_config()
        if not self.config_file:
            return False

        # Get X11 environment from GUI process
        gui_pid = self.find_gui_pid()
        if not gui_pid:
            print("❌ Could not find GUI process for X11 environment")
            return False

        x11_env = self.get_x11_environment_from_process(gui_pid)
        if not x11_env.get('DISPLAY'):
            print("❌ Could not determine DISPLAY from GUI process")
            return False

        print(f"✅ Using X11 environment from GUI process (PID: {gui_pid})")
        print(f"   DISPLAY: {x11_env.get('DISPLAY')}")
        print(f"   XAUTHORITY: {x11_env.get('XAUTHORITY', 'default')}")

        # Start xbindkeys with X11 environment
        try:
            print("🚀 Starting xbindkeys...")

            # Prepare environment
            env = os.environ.copy()
            env.update(x11_env)

            # Use nofork mode (-n) to keep xbindkeys in foreground
            self.xbindkeys_process = subprocess.Popen(
                [xbindkeys_path, '-f', self.config_file, '-n'],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                env=env
            )
            print(f"✅ xbindkeys started (PID: {self.xbindkeys_process.pid})")
            print("🎮 Listening for CTRL+ALT+SHIFT+R...")

            # Give xbindkeys a moment to start
            time.sleep(1.5)

            # Check if it's still running
            if self.xbindkeys_process.poll() is not None:
                print(f"⚠️ xbindkeys exited, will try to restart...")
                return False

            print(f"✅ xbindkeys is running and monitoring for hotkeys")
            return True

        except Exception as e:
            print(f"❌ Error starting xbindkeys: {e}")
            return False

    def run(self):
        """Start the daemon"""
        print("🚀 Whisper Hotkey Daemon starting...")
        print("📍 Monitoring for CTRL+ALT+SHIFT+R...")

        # Start xbindkeys
        if not self.start_xbindkeys():
            print("❌ Failed to start xbindkeys daemon")
            sys.exit(1)

        # Keep process running
        try:
            while self.running:
                if self.xbindkeys_process.poll() is not None:
                    # Process exited
                    print("⚠️ xbindkeys process exited, restarting...")
                    time.sleep(2)
                    if not self.start_xbindkeys():
                        break

                time.sleep(1)

        except KeyboardInterrupt:
            print("\n⏹️ Hotkey daemon stopping...")
            self.cleanup()

    def cleanup(self):
        """Clean up resources"""
        if self.xbindkeys_process:
            try:
                self.xbindkeys_process.terminate()
                self.xbindkeys_process.wait(timeout=5)
            except:
                self.xbindkeys_process.kill()

        if self.config_file and os.path.exists(self.config_file):
            try:
                os.remove(self.config_file)
                print(f"✅ Cleaned up config file: {self.config_file}")
            except Exception as e:
                print(f"⚠️ Error removing config: {e}")


if __name__ == "__main__":
    daemon = HotkeyDaemon()
    daemon.run()
